import Provider from '@/components/Provider'
import './globals.css'
import type { Metadata } from 'next'
import { Quicksand } from 'next/font/google'
import { AppContextProvider } from '@/context/AppContext'

const quicksand = Quicksand({
  subsets: ['latin'],
  weight: ['500', '600', '700']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={`${quicksand.className} bg-very-dark text-white`}>
        <Provider>
          <AppContextProvider>
            {children}
          </AppContextProvider>
        </Provider>
      </body>
    </html>
  )
}
